# 此工作流将使用 Maven 构建 Java 项目，并缓存/恢复任何依赖项以缩短工作流执行时间
# 更多信息请参阅：https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# 此工作流程使用未经 GitHub 认证的操作。
#它们由第三方提供，并受以下机构管辖：
# 单独的服务条款、隐私政策和支持
#文档。

名称： Java CI 与 Maven

在：
  推：
    修改：[    “主要”    ]
  答案：
    修改：[     “主要”     ]

工作：
  建造：

    运行于： ubuntu-latest

    步骤：
    - 用途： actions/checkout@v4
    -名称：设置JDK 17
      用途： actions/setup-java@v4
      和：
        Java 版本：'17'
        分布：'temurin'
        缓存： maven
    -名称：使用 Maven 构建
      运行： mvn -B package --file pom.xml

    # 任选：将完整的依赖关系图上传到 GitHub，以提高该存储库可以接收的 Dependabot 警报的质量
    -名称：更新依赖图-名称：更新依赖图
      用途： advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
